#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/.shplugs/Bell_Alarm
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Tue 26 Nov 20:58:47 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

bell()(
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	declare -i DEPCOUNT=0
	for DEP in pactl sleep; {
		if ! type -fP "$DEP" > /dev/null 2>&1; then
			ERR "$LINENO" "Dependency '$DEP' not met."
			DEPCOUNT+=1
		fi
	}

	[ $DEPCOUNT -eq 0 ] || return 1

	# If the module-x11-bell pactl module is loaded, continue.
	while read -a X; do
		if [ "${X[1]}" == "module-x11-bell" ]; then
			STATUS="true"
			break
		fi
	done <<< "$(pactl list modules short)"

	# Infinitely sound the bell every second.
	if [ "$STATUS" == "true" ]; then
		while :; do
			pactl play-sample x11-alert > /dev/null 2>&1
			sleep 1s
		done
	else
		ERR "$LINENO" "PulseAudio needs 'module-x11-bell' loaded."
		return 1
	fi
)

