#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/.shplugs/Cleaner_RK_Scan
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Tue 26 Nov 21:05:27 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

rkc(){
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	declare -i DEPCOUNT=0
	for DEP in sudo rkhunter chkrootkit; {
		type -fP "$DEP" > /dev/null 2>&1 || {
			ERR "$LINENO" "Dependency '$DEP' not met."
			DEPCOUNT+=1
		}
	}

	[ $DEPCOUNT -eq 0 ] || return 1

	sudo rkhunter -c --skip-keypress --rwo

	while read -r; do
		case "$REPLY" in
			*nothing\ found*)
				;;
			*not\ infected*)
				;;
			*not\ found*)
				;;
			*nothing\ detected*)
				;;
			*nothing\ deleted*)
				;;
			*no\ suspect\ files*)
				;;
			*no\ such\ file\ or\ directory)
				;;
			\!\ *)
				;;
			*)
				printf "%s\n" "$REPLY" ;;
		esac
	done <<< "$(sudo /usr/sbin/chkrootkit)"
}
