#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/.shplugs/Cleaner_RK_Scan
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Fri  6 Apr 19:54:05 BST 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

rkc(){
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	declare -i DEPCOUNT=0
	for DEP in /usr/bin/{sudo,rkhunter} /usr/sbin/chkrootkit; {
		[ -x "$DEP" ] || {
			ERR "$LINENO" "Dependency '$DEP' not met."
			DEPCOUNT+=1
		}
	}

	[ $DEPCOUNT -eq 0 ] || return 1

	/usr/bin/sudo /usr/bin/rkhunter -c --skip-keypress --rwo

	while read -r; do
		case "$REPLY" in
			*nothing\ found*)
				;;
			*not\ infected*)
				;;
			*not\ found*)
				;;
			*nothing\ detected*)
				;;
			*nothing\ deleted*)
				;;
			*no\ suspect\ files*)
				;;
			*no\ such\ file\ or\ directory)
				;;
			\!\ *)
				;;
			*)
				printf "%s\n" "$REPLY" ;;
		esac
	done <<< "$(/usr/bin/sudo /usr/sbin/chkrootkit)"
}
