#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/.shplugs/CD_Clear_LS
# Started On        - Thu 14 Sep 20:15:25 BST 2017
# Last Change       - Tue 26 Nov 21:07:16 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

CD_CLEAR_LS(){
	ERR(){ printf "ERROR: %s\n" "$2" 1>&2; }

	if type -fP ls > /dev/null 2>&1; then
		if [ $# -eq 0 ]; then
			printf "\033c"
			cd "$HOME"
			ls
		else
			printf "\033c"
			cd "$*"
			ls
		fi
	else
		ERR "$LINENO" "Dependency 'ls' not met."
		return 1
	fi
}

alias cd='CD_CLEAR_LS'
