#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/.shplugs/CPU_Intensive_Procs
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Tue 26 Nov 21:06:16 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

cpuhit(){
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	if ! type -fP ps > /dev/null 2>&1; then
		ERR "$LINENO" "Dependency 'ps' not met."
	fi

	case "${*:-EMPTY}" in
		[1-9]|10)
			;;
		*)
			ERR "$LINENO" "USAGE: cpuhit [1-10]"
			return 1 ;;
	esac

	local IFS=" "
	local COUNT=0

	printf "%-8s%-8s%s\n" "PID" "PCPU" "CMD"

	#TODO - Trying to reverse the output, the pure shell way.
	while read -ra X; do
		local PCPU="${X[1]%.*}"

		OUTPUT(){
			printf "%-8d%-8d%s\n" "${X[0]}" "$PCPU" "${X[2]}"
		}

		[ $PCPU -gt 1 ] && {
			if [ -n "$SHOW" ]; then
				local OLDSHOW="$SHOW"
				local SHOW="$PCPU"
				[ $SHOW -lt $OLDSHOW ] && OUTPUT
			else
				OUTPUT
			fi

			let COUNT++
			[ $COUNT -eq $* ] && return 0
		}
	done <<< `ps ax --noheader -o pid,pcpu,comm`
}

cpuhit 10
