#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/.shplugs/Create_VM
# Started On        - Thu 14 Sep 20:16:42 BST 2017
# Last Change       - Tue 26 Nov 21:04:02 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# A personal script I wrote when I used Virtualbox via the terminal. Some basic
# scripting knowledge might be useful here, so you could edit the relevant info to
# suit your needs.
#
# NOTE: This was used with an older version of Virtualbox, since I created it, so I
#       cannot guarantee it'll still work, as vboxmanage may now have different
#       syntax.
#----------------------------------------------------------------------------------

# $1 = Name
# $2 = Type

mkvm(){
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	if ! type -fP vboxmanage > /dev/null 2>&1; then
		ERR "$LINENO" "Dependency '/usr/bin/vboxmanage' not met."
		return 1
	elif ! [ $# -eq 2 ]; then
		ERR "$LINENO" "Correct syntax is 'mkvm <name> <ostype>'."
		return 1
	elif [ -z "$VBOX_USER_HOME" ]; then
		ERR "$LINENO" "Environment variable 'VBOX_USER_HOME' not set."
		return 1
	fi

	{
		printf "Creating and registering the virtual machine.\n"
		vboxmanage createvm                                      \
			--name "$1"                                               \
			--ostype "$2"                                             \
			--basefolder "$VBOX_USER_HOME"                            \
			--register

		printf "Creating the 12GB dynamic storage drive.\n"
		vboxmanage createmedium                                  \
			--filename "$VBOX_USER_HOME/$1/$1"                        \
			--size 12000                                              \
			--format VDI                                              \
			--variant Standard

		printf "Configuring the new virtual machine.\n"
		vboxmanage modifyvm "$1"                                 \
			--usb off                                                 \
			--audio pulse                                             \
			--bioslogofadein off                                      \
			--bioslogofadeout off                                     \
			--bioslogodisplaytime 0                                   \
			--biosbootmenu menuonly                                   \
			--audiocontroller ac97                                    \
			--clipboard disabled                                      \
			--monitorcount 1                                          \
			--draganddrop disabled                                    \
			--mouse ps2                                               \
			--keyboard ps2                                            \
			--boot1 dvd                                               \
			--boot2 disk                                              \
			--boot3 floppy                                            \
			--vram 128                                                \
			--memory 2048                                             \
			--cpuexecutioncap 95                                      \
			--hostkey 305 128                                         \
			--cpus 3                                                  \
			--paravirtprovider kvm                                    \
			--pae on                                                  \
			--chipset ich9                                            \
			--graphicscontroller vboxvga                              \
			--hwvirtex on                                             \
			--accelerate3d on                                         \
			--accelerate2dvideo off                                   \
			--firmware bios

		printf "Setting up the FDD controller.\n"
		vboxmanage storagectl "$1"                               \
			--name "Floppy Controller"                                \
			--add floppy

		printf "Setting up the IDE controller.\n"
		vboxmanage storagectl "$1"                               \
			--name "IDE Controller"                                   \
			--add ide

		printf "Adding the primary HDD.\n"
		vboxmanage storageattach "$1"                            \
			--storagectl "IDE Controller"                             \
			--port 1                                                  \
			--device 1                                                \
			--type hdd                                                \
			--medium "$VBOX_USER_HOME"/$1/${1}.vdi

		printf "Adding the primary FDD.\n"
		vboxmanage storageattach "$1"                            \
			--storagectl "Floppy Controller"                          \
			--port 0                                                  \
			--device 1                                                \
			--type fdd                                                \
			--medium "$VBOX_USER_HOME"/vboxtransfer.img
	} || ERR "$LINENO" "Virtual machine creation failure."
}

