#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/.shplugs/Get_Bad_Hosts
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Thu 17 Jan 17:33:13 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

#TODO - Defunct, because link is no longer available. Find and set a new one.
gbh(){
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	if ! [ -x /usr/bin/wget ]; then
		ERR "$LINENO" "Dependency '/usr/bin/wget' not met."
		return 1
	elif ! [ $# -eq 0 ]; then
		ERR "$LINENO" "No arguments required."
		return 1
	fi

	URL="http://www.montanamenagerie.org/hostsfile/hosts.txt"
	DESTINATION="$HOME/Downloads/GBH.txt"
	if ! [ -d "${DESTINATION%\/*}" ]; then
		ERR "$LINENO" "Destination directory not found."
		return 1
	elif [ -f "${DESTINATION}.gz" ]; then
		ERR "$LINENO" "File already present."
		return 1
	else
		while read -a X; do
			if [ "${X[0]}" == "127.0.0.1" ]; then
				printf "%s %s\n" "${X[0]}" "${X[1]%}"
			fi
		done <<< "$(/usr/bin/wget $NOWARC -q "$URL" -O -)"\
			> ./Bad\ Hosts.txt
	fi
}

