#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/.shplugs/Load_File_Links2
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Tue 26 Nov 21:08:32 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

l2f(){
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	if ! [ $# -gt 0 ]; then
		ERR "$LINENO" "Please specify a file to be read."
		return 1
	else
		if type -fP links2 > /dev/null 2>&1; then
			links2 -force-html file://"$*"
		else
			ERR "$LINENO" "Dependency 'links2' not found."
			return 1
		fi
	fi
}

