#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/.shplugs/Loop_This
# Started On        - Thu  2 Nov 18:52:49 GMT 2017
# Last Change       - Tue 26 Nov 21:07:32 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Doesn't seem to work, unless I've just forgotten something key. I believe the
# purpose of this script was to somewhat mimic the watch command, albeit basically.
#----------------------------------------------------------------------------------

loop(){
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	if ! type -fP sleep > /dev/null 2>&1; then
		ERR "$LINENO" "Dependency 'sleep' not met."
		return 1
	elif [ $# -eq 0 ]; then
		ERR "$LINENO" "Command(s) required before looping can begin."
		return 1
	else
		printf "\ec"
		while :; do
			printf "\ec\eH"
			sleep 0.3
			$@
		done
	fi
}

