#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/.shplugs/Shell_Alias_Correcting
# Started On        - Fri 15 Sep 15:20:17 BST 2017
# Last Change       - Fri  6 Apr 19:54:49 BST 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

# The cd command:
alias cd..='cd ..'
alias vf='cd'
alias xs='cd'

# The ls command:
alias ld='/bin/ls'
alias la='/bin/ls'
alias lsd='/bin/ls'
alias sl='/bin/ls'
alias ks='/bin/ls'

# The clear command:
alias lcear='/usr/bin/clear'
alias celar='/usr/bin/clear'
alias clea='/usr/bin/clear'
alias clre='/usr/bin/clear'
alias ckear='/usr/bin/clear'
alias cear='/usr/bin/clear'
alias caer='/usr/bin/clear'
alias lcaer='/usr/bin/clear'
alias lear='/usr/bin/clear'
alias cler='/usr/bin/clear'
alias clera='/usr/bin/clear'

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
