#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/lad
# Started On        - Tue  9 Apr 14:48:44 BST 2019
# Last Change       - Tue  9 Apr 18:56:16 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-04-09"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            LAD - LIST AND DESCRIBE ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            List and describe functions and aliases made available from the
		            bashconfig repository, found through the GitHub link below.

		SYNTAX:     lad [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --debug|-D              - Enables the built-in bash debugging.

		FILES:      The following files are scanned:

		              \$HOME/.bash_functions
		              \$HOME/.bash_aliases

		LINK:       https://github.com/terminalforlife
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac
	shift
done

[ "$DEBUGME" == "true" ] && set -x

FILE_BF="$HOME/.bash_functions"
FILE_BA="$HOME/.bash_aliases"

#------------------------------------------------------------------GATHER FUNCTIONS

if [ -f "$FILE_BF" ] && [ -r "$FILE_BF" ]; then
	printf "FUNCTIONS ($FILE_BF)\n\n"

	while read; do
		if ! [ -z "$REPLY" ] && ! [[ "$REPLY" =~ ^\# ]]; then
			if [[ "$REPLY" =~ [a-Z0-9_-]+\(\)\{ ]]; then
				NAME="${REPLY%%\(\)\{*}"

				# A description of " #: TEXT" must be appended to
				# the function call line for each function. This
				# will NOT work otherwise.
				DESC="${REPLY#*\#\:}"

				# Only functions found 0-1 tabs in are counted.
				if ! [[ "$NAME" =~ \	{2,} ]]; then
					printf "  %s - %s\n" $NAME "${DESC#\ }"
				fi
			fi
		fi
	done < "$FILE_BF"
else
	XERR "$LINENO" "File '$FILE_BF' not found."
fi

#--------------------------------------------------------------------GATHER ALIASES

if [ -f "$FILE_BA" ] && [ -r "$FILE_BA" ]; then
	printf "\nALIASES ($FILE_BA)\n\n"

	while read; do
		if ! [ -z "$REPLY" ] && ! [[ "$REPLY" =~ ^\# ]]; then
			if [[ "$REPLY" =~ alias\ [:\"\']{0,}[a-Z0-9_-]+[\'\"]{0,}\= ]]; then
				declare -a TEMP=(${REPLY%%\=*})

				#TODO - A cleaner system is preferable.
				# A description of " #: TEXT" must be appended to
				# the alias set line for each function. This will
				# NOT work otherwise, as with the functions.
				DESC="${REPLY#*\#\:}"

				if [ "${TEMP[0]}" == "alias" ]; then
					printf "  %s - %s\n" "${TEMP[1]//[\"\']}" "${DESC#\ }"

				fi
			fi
		fi
	done < "$FILE_BA"
else
	XERR "$LINENO" "File '$FILE_BA' not found."
fi
