#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/list_commands
# Started On        - Tue  9 Apr 14:48:44 BST 2019
# Last Change       - Tue  9 Apr 15:39:03 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-04-09"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            LIST_COMMANDS ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            List available commands made available from the bashconfig repository
		            found through the link below.

		SYNTAX:     list_commands [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --debug|-D              - Enables the built-in bash debugging.

		LINK:       https://github.com/terminalforlife
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac
	shift
done

#declare -i DEPCOUNT=0
#for DEP in PATH; {
#	if ! [ -x "$DEP" ]; then
#		ERR "$LINENO" "Dependency '$DEP' not met."
#		DEPCOUNT+=1
#	fi
#}
#
#[ $DEPCOUNT -eq 0 ] || exit 1

[ "$DEBUGME" == "true" ] && set -x

FILE_BF="$HOME/.bash_functions"
FILE_BA="$HOME/.bash_aliases"

if [ -f "$FILE_BF" ] && [ -r "$FILE_BF" ]; then
	while read; do
		if ! [ -z "$REPLY" ] && ! [[ "$REPLY" =~ ^\# ]]; then
			if [[ "$REPLY" =~ [a-Z0-9_-]+\(\)\{ ]]; then
				declare NAME="${REPLY%%\(\)\{*}"

				# A description of " #: TEXT" must be appended to
				# the function call line for each function. This
				# will NOT work otherwise.
				declare DESC="${REPLY#*\#\:}"

				# Only functions found 0-1 tabs in are counted.
				if ! [[ "$NAME" =~ \	{2,} ]]; then
					printf "%s - %s\n" $NAME "$DESC"
				fi
			fi
		fi
	done < "$FILE_BF"
else
	XERR "$LINENO" "File '$HOME/.bash_functions' not found."
fi
