#!/bin/bash
# Written by terminalforlife (terminalforlife@yahoo.com)

ETC_BC_FILE="/etc/bash_completion"
USR_BC_FILE="/usr/share/bash-completion/bash_completion"

if [ -f "$USR_BC_FILE" ]
then
	source "$USR_BC_FILE"
elif [ -f "$ETC_BC_FILE" ]
then
	source "$ETC_BC_FILE"
fi

unset ETC_BC_FILE USR_BC_FILE
