#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/Bell_Alarm
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Thu 12 Oct 15:59:00 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

bell(){
	# Load error functions.
	RERR(){ echo "[L${1}] ERROR: $2" 1>&2; return 1; }
	ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }
	
	# Check for dependencies.
	declare -i DEPCOUNT=0
	for DEP in /usr/bin/pactl /bin/sleep; {
		[ -x "$DEP" ] || {
			ERR "$LINENO" "Dependency '$DEP' not met."
			DEPCOUNT+=1
		}
	}
	
	# Return if any dependencies are unmet.
	[ $DEPCOUNT -eq 0 ] || return 1

	# Check for root access.
	[ $UID -eq 0 ] && RERR "$LINENO" "Root access isn't required."

	# If the module-x11-bell pactl module is loaded, continue.
	while read -r; do
		[[ "$REPLY" == ?Name:\ module-x11-bell ]] && {
			# Infinitely sound the bell every second.
			while :; do
				printf "\a"
				/bin/sleep 1
			done

			return
		}
	done <<< "$(/usr/bin/pactl list modules)"

	# If module not loaded, output error and return 1.
	RERR "$LINENO" "PulseAudio needs 'module-x11-bell' loaded."
}
