#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/Bell_Alarm
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Fri 15 Sep 14:51:49 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

bell()
{
	RERR(){ echo "ERROR: $1" 1>&2; return; }
	ERR(){ echo "ERROR: $1" 1>&2; }
	
	[ $UID -eq 0 ] && RERR "Root access isn't required."
	
	DEPCOUNT=0
	for DEP in /usr/bin/pactl /bin/{grep,sleep}
	{
		if ! type -P "$DEP" &> /dev/null
		then
			ERR "Dependency '$DEP' not met."
			let DEPCOUNT++
		fi
	}
	
	[ $DEPCOUNT -eq 0 ] || return

	if /usr/bin/pactl list modules | /bin/grep -q "module-x11-bell"
	then
		while :
		do
			printf "\a"
			/bin/sleep 1
		done
	else
		echo "ERROR: PulseAudio needs 'module-x11-bell' loaded." 1>&2
		echo "       Execute 'pactl list modules' to double-check." 1>&2
		return
	fi
}
