#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/CD_Clear_LS
# Started On        - Thu 14 Sep 20:15:25 BST 2017
# Last Change       - Fri 19 Jan 22:22:40 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

CD_CLEAR_LS(){
	ERR(){ printf "ERROR: %s\n" "$2" 1>&2; }

	if [ -x /bin/ls ]; then
		if [ $# -eq 0 ]; then
			printf "\033c"
			cd "$HOME"
			/bin/ls
		else
			printf "\033c"
			cd "$*"
			/bin/ls
		fi
	else
		ERR "$LINENO" "Dependency 'ls' not met."
		return 1
	fi
}

alias cd='CD_CLEAR_LS'

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
