#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/Cleaner_RK_Scan
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Fri 15 Sep 14:52:30 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

rkc()
{
	RERR(){ echo "ERROR: $1" 1>&2; return; }
	ERR(){ echo "ERROR: $1" 1>&2; }
	
	[ $UID -eq 0 ] && RERR "Root access isn't required."
	
	DEPCOUNT=0
	for DEP in /usr/bin/rkhunter /bin/sed /sbin/chkrootkit
	{
		if ! type -P "$DEP" &> /dev/null
		then
			ERR "Dependency '$DEP' not met."
			let DEPCOUNT++
		fi
	}
	
	[ $DEPCOUNT -eq 0 ] || return

	/usr/bin/rkhunter -c --skip-keypress --rwo

	/bin/sed '
		/nothing found/d;
		/not infected/d;
		/not found/d;
		/nothing detected/d;
		/nothing deleted/d;
		/no suspect files/d;
		/no such file or directory/d
	' <<< "$(/usr/sbin/chkrootkit)"
}
