#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/Cleaner_RK_Scan
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Thu 12 Oct 15:47:31 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

rkc(){
	ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }
	
	declare -i DEPCOUNT=0
	for DEP in /usr/bin/{sudo,rkhunter} /usr/sbin/chkrootkit; {
		[ -x "$DEP" ] || {
			ERR "$LINENO" "Dependency '$DEP' not met."
			DEPCOUNT+=1
		}
	}
	
	[ $DEPCOUNT -eq 0 ] || return 1

	/usr/bin/sudo /usr/bin/rkhunter -c --skip-keypress --rwo

	while read -r; do
		case "$REPLY" in
			*nothing\ found*)
				;;
			*not\ infected*)
				;;
			*not\ found*)
				;;
			*nothing\ detected*)
				;;
			*nothing\ deleted*)
				;;
			*no\ suspect\ files*)
				;;
			*no\ such\ file\ or\ directory)
				;;
			\!\ *)
				;;
			*)
				echo "$REPLY" ;;
		esac
	done <<< "$(/usr/bin/sudo /usr/sbin/chkrootkit)"
}
