#!/bin/bash
# Written by terminalforlife (terminalforlife@yahoo.com)

cpuhit()
{
	if [ $# -eq 0 ] || [ $# -gt 1 ]
	then
		echo "USAGE: cpuhit [1-10]" 1>&2
		return
	fi

	if [ "$1" -lt 1 ] || [ "$1" -gt 10 ]
	then
		echo "Argument '$1' is out of the 1 to 10 range." 1>&2
		return
	fi

	ps -eo pcpu,pid\
		| /usr/bin/sort -k 1 -rn\
		| /usr/bin/awk -Sv var=$1 'NR==1,NR==var {print $1"%","("$2")"}'
}
