#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/CPU_Intensive_Procs
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Thu  5 Oct 18:05:47 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

cpuhit(){
	RERR(){ echo "[L${1}] ERROR: $2" 1>&2; return 1; }

	[ -x /bin/ps ] && {
		RERR "$LINENO" "Dependency '/bin/ps' not met." || return 1
	}

	case "${*:-EMPTY}" in
		[1-9]|10)
			;;
		*)
			RERR "$LINENO" "USAGE: cpuhit [1-10]" || return 1 ;;
	esac

	local IFS=" "
	local COUNT=0

	#TODO - Trying to reverse the output, the pure shell way.
	while read -r -a REPLY; do
		local PCPU="${REPLY[1]%.*}"

		OUTPUT(){
			printf "%d %d %s\n" "${REPLY[0]}" "$PCPU" "${REPLY[2]}"
		}

		[ $PCPU -gt 1 ] && {
			if [ -n "$SHOW" ]
			then
				local OLDSHOW="$SHOW"
				local SHOW="$PCPU"
				[ $SHOW -lt $OLDSHOW ] && OUTPUT
			else
				OUTPUT
			fi

			let COUNT++; [ $COUNT -eq $* ] && return 0
		}
	done <<< `/bin/ps ax --noheader -o pid,pcpu,comm`
}
