#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/CPU_Intensive_Procs
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Fri 13 Oct 23:44:56 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

cpuhit(){
	ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }

	[ -x /bin/ps ] || ERR "$LINENO" "Dependency '/bin/ps' not met."

	case "${*:-EMPTY}" in
		[1-9]|10)
			;;
		*)
			ERR "$LINENO" "USAGE: cpuhit [1-10]"
			return 1 ;;
	esac

	local IFS=" "
	local COUNT=0

	printf "%-8s%-8s%s\n" "PID" "PCPU" "CMD"

	#TODO - Trying to reverse the output, the pure shell way.
	while read -r -a REPLY; do
		local PCPU="${REPLY[1]%.*}"

		OUTPUT(){
			printf "%-8d%-8d%s\n" "${REPLY[0]}" "$PCPU" "${REPLY[2]}"
		}

		[ $PCPU -gt 1 ] && {
			if [ -n "$SHOW" ]; then
				local OLDSHOW="$SHOW"
				local SHOW="$PCPU"
				[ $SHOW -lt $OLDSHOW ] && OUTPUT
			else
				OUTPUT
			fi

			let COUNT++
			[ $COUNT -eq $* ] && return 0
		}
	done <<< `/bin/ps ax --noheader -o pid,pcpu,comm`
}
