#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/Create_VM
# Started On        - Thu 14 Sep 20:16:42 BST 2017
# Last Change       - Fri 15 Sep 15:01:40 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

# $1 = Name
# $2 = Type

mkvm()
{
	RERR(){ echo "ERROR: $1" 1>&2; return; }
	ERR(){ echo "ERROR: $1" 1>&2; }

	[ $UID -eq 0 ] && RERR "Root access isn't required."
	
	if ! type -P "$DEP" &> /dev/null
	then
		ERR "Dependency '/usr/bin/vboxmanage' not met."
		return
	fi

	if ! [ $# -eq 2 ]
	then
		RERR "Correct syntax is 'mkvm <name> <ostype>'."
	fi

	if [ -z "$VBOX_USER_HOME" ]
	then
		RERR "Environment variable 'VBOX_USER_HOME' not set."
	fi
	
	(
		echo "Creating and registering the virtual machine."
		/usr/bin/vboxmanage createvm                              \
			--name "$1"                                       \
			--ostype "$2"                                     \
			--basefolder "$VBOX_USER_HOME"                    \
			--register
		
		echo "Creating the primary storage medium."
		/usr/bin/vboxmanage createmedium                          \
			--filename "$VBOX_USER_HOME/$1/$1"                \
			--size 12000                                      \
			--format VDI                                      \
			--variant Standard

		echo "Configuring the new virtual machine."
		/usr/bin/vboxmanage modifyvm "$1"                         \
			--usb off                                         \
			--audio pulse                                     \
			--bioslogofadein off                              \
			--bioslogofadeout off                             \
			--bioslogodisplaytime 0                           \
			--biosbootmenu menuonly                           \
			--audiocontroller ac97                            \
			--clipboard disabled                              \
			--monitorcount 1                                  \
			--draganddrop disabled                            \
			--mouse ps2                                       \
			--keyboard ps2                                    \
			--boot1 dvd                                       \
			--boot2 disk                                      \
			--boot3 floppy                                    \
			--vram 128                                        \
			--memory 2048                                     \
			--cpuexecutioncap 95                              \
			--cpus 3                                          \
			--paravirtprovider kvm                            \
			--pae on                                          \
			--chipset ich9                                    \
			--graphicscontroller vboxvga                      \
			--hwvirtex on                                     \
			--accelerate3d on                                 \
			--accelerate2dvideo off                           \
			--firmware bios

		echo "Setting up the FDD controller."
		/usr/bin/vboxmanage storagectl "$1"                       \
		                                                          \
			--name "Floppy Controller"                        \
			--add floppy

		echo "Setting up the IDE controller."
		/usr/bin/vboxmanage storagectl "$1"                       \
		                                                          \
			--name "IDE Controller"                           \
			--add ide

		echo "Adding the primary HDD."
		/usr/bin/vboxmanage storageattach "$1"                    \
		                                                          \
			--storagectl "IDE Controller"                     \
			--port 1                                          \
			--device 1                                        \
			--type hdd                                        \
			--medium "$VBOX_USER_HOME"/$1/${1}.vdi

		echo "Adding the primary FDD."
		/usr/bin/vboxmanage storageattach "$1"                    \
		                                                          \
			--storagectl "Floppy Controller"                  \
			--port 0                                          \
			--device 1                                        \
			--type fdd                                        \
			--medium "$VBOX_USER_HOME"/vboxtransfer.img
	) &> /dev/null

	echo "Virtual machine has been created... hopefully."

	# --hostkey 305 128
}
