#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/ShellPlugins/Create_VM
# Started On        - Thu 14 Sep 20:16:42 BST 2017
# Last Change       - Fri  6 Apr 19:54:17 BST 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

# $1 = Name
# $2 = Type

mkvm(){
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	if ! [ -x /usr/bin/vboxmanage ]; then
		ERR "$LINENO" "Dependency '/usr/bin/vboxmanage' not met."
		return 1
	elif ! [ $# -eq 2 ]; then
		ERR "$LINENO" "Correct syntax is 'mkvm <name> <ostype>'."
		return 1
	elif [ -z "$VBOX_USER_HOME" ]; then
		ERR "$LINENO" "Environment variable 'VBOX_USER_HOME' not set."
		return 1
	fi

	{
		printf "Creating and registering the virtual machine.\n"
		/usr/bin/vboxmanage createvm                                      \
			--name "$1"                                               \
			--ostype "$2"                                             \
			--basefolder "$VBOX_USER_HOME"                            \
			--register

		printf "Creating the 12GB dynamic storage drive.\n"
		/usr/bin/vboxmanage createmedium                                  \
			--filename "$VBOX_USER_HOME/$1/$1"                        \
			--size 12000                                              \
			--format VDI                                              \
			--variant Standard

		printf "Configuring the new virtual machine.\n"
		/usr/bin/vboxmanage modifyvm "$1"                                 \
			--usb off                                                 \
			--audio pulse                                             \
			--bioslogofadein off                                      \
			--bioslogofadeout off                                     \
			--bioslogodisplaytime 0                                   \
			--biosbootmenu menuonly                                   \
			--audiocontroller ac97                                    \
			--clipboard disabled                                      \
			--monitorcount 1                                          \
			--draganddrop disabled                                    \
			--mouse ps2                                               \
			--keyboard ps2                                            \
			--boot1 dvd                                               \
			--boot2 disk                                              \
			--boot3 floppy                                            \
			--vram 128                                                \
			--memory 2048                                             \
			--cpuexecutioncap 95                                      \
			--hostkey 305 128                                         \
			--cpus 3                                                  \
			--paravirtprovider kvm                                    \
			--pae on                                                  \
			--chipset ich9                                            \
			--graphicscontroller vboxvga                              \
			--hwvirtex on                                             \
			--accelerate3d on                                         \
			--accelerate2dvideo off                                   \
			--firmware bios

		printf "Setting up the FDD controller.\n"
		/usr/bin/vboxmanage storagectl "$1"                               \
			--name "Floppy Controller"                                \
			--add floppy

		printf "Setting up the IDE controller.\n"
		/usr/bin/vboxmanage storagectl "$1"                               \
			--name "IDE Controller"                                   \
			--add ide

		printf "Adding the primary HDD.\n"
		/usr/bin/vboxmanage storageattach "$1"                            \
			--storagectl "IDE Controller"                             \
			--port 1                                                  \
			--device 1                                                \
			--type hdd                                                \
			--medium "$VBOX_USER_HOME"/$1/${1}.vdi

		printf "Adding the primary FDD.\n"
		/usr/bin/vboxmanage storageattach "$1"                            \
			--storagectl "Floppy Controller"                          \
			--port 0                                                  \
			--device 1                                                \
			--type fdd                                                \
			--medium "$VBOX_USER_HOME"/vboxtransfer.img
	} || ERR "$LINENO" "Virtual machine creation failure."
}

# vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
