#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/Get_Bad_Hosts
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Fri 15 Sep 15:07:51 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

# WORK IN PROGRESS

gbh()
{
	RERR(){ echo "ERROR: $1" 1>&2; return; }
	ERR(){ echo "ERROR: $1" 1>&2; }
	
	[ $UID -eq 0 ] && RERR "Root access isn't required."
	
	DEPCOUNT=0
	for DEP in /bin/{cat,grep,gzip} /usr/bin/{wget,dos2unix,uniq,sort,tr}
	{
		if ! type -P "$DEP" &> /dev/null
		then
			ERR "Dependency '$DEP' not met."
			let DEPCOUNT++
		fi
	}
	
	[ $DEPCOUNT -eq 0 ] || return

	if ! [ $# -eq 0 ]
	then
		RERR "ERROR: No arguments required."
	fi

	URL="http://www.montanamenagerie.org/hostsfile/hosts.txt"
	DESTINATION="$HOME/Downloads/GBH.txt"

	if ! [ -d "${DESTINATION%\/*}" ]
	then
		RERR "Destination directory not found."
	fi

	if [ -f "${DESTINATION}.gz" ]
	then
		RERR "ERROR: File already present."
	fi

	/usr/bin/wget -q --show-progress "$URL" -O "$DESTINATION"
	/usr/bin/dos2unix "$DESTINATION"

	/bin/cat "$DESTINATION"\
		| /usr/bin/tr "\t" " "\
		| /bin/grep -a "^127.0.0.1 "\
		| /usr/bin/uniq\
		| /usr/bin/sort\
		| /bin/gzip -c\
		> "$DESTINATION"

}
