#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/List_Signals
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Mon 30 Oct 02:01:03 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

# Admittedly, this probably isn't all that useful. There are various ways already
# to list the various signal, but I used it as an educational exercise, more than
# anything.
#
# Alternative, run "kill -l", "killall -l", trap -l, or "skill -L"

#----------------------------------------------------------------------------------

lssig(){
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	[ $UID -eq 0 ] && {
		ERR "$LINENO" "Root access isn't required."
		return 1
	}

	[ $# -gt 0 ] && {
		ERR "$LINENO" "No arguments are required."
		return 1
	}

	[ -x /usr/bin/column ] && {
		NUM=0
		for SIG in\
		\
			1:HUP 2:INT 3:QUIT 4:ILL 5:TRAP 6:ABRT 7:BUS 8:FPE\
			9:KILL 10:USR1 11:SEGV 12:USR2 13:PIPE 14:ALRM\
			15:TERM 16:STKFLT 17:CHLD 18:CONT 19:STOP 20:TSTP\
			21:TTIN 22:TTOU 23:URG 24:XCPU 25:XFSZ 26:VTALRM\
			27:PROF 28:WINCH 29:POLL 30:PWR 31:SYS;
		{
			let NUM++
			printf "%2d %s\n" "${NUM%:*}" "${SIG/*:}"
		} | /usr/bin/column -x
	} || {
		ERR "$LINENO" "Dependency '/usr/bin/column' not met."
		return 1
	}
}

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
