#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/Load_File_Links2
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Fri 15 Sep 15:12:29 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

l2f()
{
	RERR(){ echo "ERROR: $1" 1>&2; return; }

	[ $UID -eq 0 ] && RERR "Root access isn't recommended."
	[ $# -gt 0 ] || RERR "Please specify a file to be read."

	if type -P /usr/bin/links2 &> /dev/null
	then
		/usr/bin/links2 -force-html file://"$@"
	else
		RERR "Dependency '/usr/bin/links2' not found."
	fi
}
