#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bashconfig/ShellPlugins/Loop_This
# Started On        - Thu  2 Nov 18:52:49 GMT 2017
# Last Change       - Fri  6 Apr 19:54:36 BST 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

loop(){
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	if ! [ -x /bin/sleep ]; then
		ERR "$LINENO" "Dependency '/bin/sleep' not met."
		return 1
	elif [ $# -eq 0 ]; then
		ERR "$LINENO" "Command(s) required before looping can begin."
		return 1
	else
		printf "\ec"
		while :; do
			printf "\ec\eH"
			/bin/sleep 0.3
			$@
		done
	fi
}

# vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
