#!/bin/bash
# Written by terminalforlife (terminalforlife@yahoo.com)

LS_INSTALLED_PKGS()
{
	if ! [ $# -eq 0 ]
	then
		echo "ERROR: No arguments are required." 1>&2
		return
	fi

	DEPCOUNT=0
	for DEP in /usr/bin/{dpkg-query,cut,uniq} /bin/grep
	{
		if ! type -P "$DEP" 2>&1 > /dev/null
		then
			echo "ERROR: Dependency '$DEP' unmet." 1>&2
			let DEPCOUNT++
		fi
	}

	[ $DEPCOUNT -gt 0 ] && return

	FORMAT="\${db:Status-Abbrev} \${Package} - \${binary:Summary}\n"
	/usr/bin/dpkg-query --show -f="$FORMAT" \*\
		| /bin/grep "^ii"\
		| /usr/bin/cut -d " " -f 3-\
		| /usr/bin/uniq
}
