#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/NIR_Difference
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Thu  8 Mar 05:28:44 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This was something I wrote a while back, because I was curious to see the
# difference of the number of packages which needed to be installed when using the
# apt-get "--no-install-recommends" flag, VS not using it.
#
# In retrospect, I could totally have done this better and more concisely, but it
# was written a while ago. Still, using it on packages like lightdm is interesting.
#----------------------------------------------------------------------------------

nirdiff(){
	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

	[ $# -gt 1 ] || {
		ERR "$LINENO" "Please specify a package name."
		return 1
	}

	declare -i DEPCOUNT=0
	for DEP in /usr/bin/{apt-get,awk,dpkg-query}; {
		[ -x "$DEP" ] || {
			ERR "$LINENO" "Dependency '$DEP' not met."
			DEPCOUNT+=1
		}
	}

	[ $DEPCOUNT -eq 0 ] || return 1

	if /usr/bin/dpkg-query --status "$1" &> /dev/null; then
		RERR "$LINENO" "Package already installed."
	elif ! /usr/bin/dpkg-query --show "$1" &> /dev/null; then
		RERR "$LINENO" "Package '$1' not found."
	fi

	printf "%-25s%10s\n" "FLAG" "PKG"

	for SIM in "--no-" "--"; {
		/usr/bin/apt-get install -s ${SIM}install-recommends "$1" 2> /dev/null\
			| /usr/bin/awk -Sv SIM="$SIM" '
				{
					if(/^[0-9]+ to upgrade,\s/)
						printf "%-25s%10d\n",SIM"install-recommends",$4
				}'
	}
}

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
