#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/NIR_Difference
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Tue  3 Oct 18:27:20 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

nirdiff(){
	RERR(){ echo "ERROR: $1" 1>&2; return 1; }

	[ $UID -eq 0 ] && RERR "Root access isn't required."
	[ $# -gt 1 ] || RERR "Please specify a package name."

	declare -i DEPCOUNT=0
	for DEP in /usr/bin/{apt-get,awk,dpkg-query}; {
		[ -x "$DEP" ] || {
			ERR "Dependency '$DEP' not met."
			DEPCOUNT+=1
		{
	}
	
	[ $DEPCOUNT -eq 0 ] || exit 1

	if /usr/bin/dpkg-query --status "$1" &> /dev/null; then
		RERR "Package already installed."
	elif ! /usr/bin/dpkg-query --show "$1" &> /dev/null; then
		RERR "Package '$1' not found."
	fi

	printf "%-25s%10s\n" "FLAG" "PKG"

	for SIM in "--no-" "--"; {
		/usr/bin/apt-get install -s ${SIM}install-recommends "$1" 2> /dev/null\
			| /usr/bin/awk -Sv SIM="$SIM" '
				{
					if(/^[0-9]+ to upgrade,\s/)
						printf "%-25s%10d\n",SIM"install-recommends",$4
				}'
	}
}
