#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/Play_Download_MPSYT
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Fri 13 Oct 23:54:57 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

yt(){
	ARG_FAIL(){ echo "USAGE: yt [-p|-d] URL" 1>&2; }
	ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }

	[ $UID -eq 0 ] && {
		ERR "$LINENO" "Root access isn't required."
		return 1
	}

	[ $# -gt 1 ] || {
		ERR "$LINENO" "Please specify a package name."
		return 1
	}

	declare -i DEPCOUNT=0
	for DEP in /usr/bin/{apt-get,awk,dpkg-query}; {
		[ -x "$DEP" ] || {
			ERR "$LINENO" "Dependency '$DEP' not met."
			DEPCOUNT+=1
		}
	}
	
	[ $DEPCOUNT -eq 0 ] || exit 1

	if [ $# -gt 2 ]; then
		ARG_FAIL; return 1
	elif [ "$1" == "-p" ]; then
		/usr/bin/mpsyt playurl "$2"
	elif [ "$1" == "-d" ]; then
		/usr/bin/mpsyt dlurl "$2"
	else
		ARG_FAIL; return 1
	fi
}

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
