#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/Bell_Alarm
# Started On        - Thu 14 Sep 20:10:21 BST 2017
# Last Change       - Wed 14 Feb 16:26:08 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

case `printf "%(%F)T" -1` in
	2018-02-14) printf "REMINDER: It's St. Valentine's Day.\n" ;;
	2018-12-24) printf "REMINDER: It's Christmas Eve.\n" ;;
	2018-12-25) printf "REMINDER: It's Christmas Day.\n" ;;
	2019-01-01) printf "REMINDER: It's New Year's day.\n" ;;
esac

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
