#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/Times_Table
# Started On        - Fri 15 Sep 15:20:17 BST 2017
# Last Change       - Mon 23 Oct 13:17:28 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

tentt(){
	printf "%4d" {1..10}; echo
	printf "%4d" {2..20..2}; echo
	printf "%4d" {3..30..3}; echo
	printf "%4d" {4..40..4}; echo
	printf "%4d" {5..50..5}; echo
	printf "%4d" {6..60..6}; echo
	printf "%4d" {6..70..7}; echo
	printf "%4d" {8..80..8}; echo
	printf "%4d" {9..90..9}; echo
	printf "%4d" {10..100..10}; echo
}

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
