#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/bin/lad
#----------------------------------------------------------------------------------
# Project Name      - BashConfig/source/lad (List and Describe)
# Started On        - Tue  9 Apr 14:48:44 BST 2019
# Last Change       - Sun  8 Dec 20:54:39 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep

CurVer='2019-12-08'
Progrm=${0##*/}

Usage(){
	while read; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${Progrm^^} ($CurVer)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            List and describe supported functions and aliases.

		SYNTAX:     $Progrm [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --debug|-D              - Enables the built-in Bash debugging.
		            --funcs|-F              - Display only functions.
		            --aliases|-A            - Display only aliases.

		RULES:      In order for $Progrm to correctly list functions and aliases, various rules
		            must be followed; these are listed below:

		              1. ' #: ', sans quotes, must be appended to alias lines.

		                 For example:

		                   alias do='echo "Some random stuff."' #: Print some text.

		              2. Alias setting MUST be single-line only.

		              3. ' #: ', sans quotes, must be appended to function declaration.

		                 For example:

		                   func_name(){ #: Print some text.
		                           echo "Some random stuff."
		                   }

		              4. The alias must be the first command on its line.

		                 Example of incorrect usage:

		                   [ -x /bin/thing ] && alias do="thing" #: Do thing.

		                 Example of correct usage:

		                   if [ -x /bin/thing ]; then
		                           alias do="thing" #: Do thing.
		                   fi

		              5. Aliases must be put into: ~/.bash_aliases

		              6. Functions must be put into: ~/.bash_functions

		              7. Functions must use '(){', without spacing. You can, however, use
		                 parentheses instead of braces, for use of sub-shells.

		FILES:      The following files are scanned:

		              ~/.bash_functions
		              ~/.bash_aliases

		LINK:       https://github.com/terminalforlife/BashConfig
	EOF
}

NL="\n"

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf "%s\n" "$CurVer"
			exit 0 ;;
		--debug|-D)
			DebugMe='true' ;;
		--funcs|-F)
			OnlyFunc='true' ;;
		--aliases|-A)
			OnlyAlias='true'; unset NL ;;
		*)
			Err 1 "Incorrect argument(s) specified." ;;
	esac
	shift
done

if [ -n "$OnlyFunc" -a -n "$OnlyAlias" ]; then
	Err 1 "Either '--only-funcs|-F' or '--only-aliases|-A' may used at one time."
fi

FileBF="$HOME/.bash_functions"
FileBA="$HOME/.bash_aliases"

[ "$DebugMe" == 'true' ] && set -x

Print(){ printf "  %s - %s\n" "$@"; }

# Gather functions.
if [ "$OnlyFunc" == 'true' ] || [ -z "$OnlyFunc" -a -z "$OnlyAlias" ]; then
	if [ -f "$FileBF" ] && [ -r "$FileBF" ]; then
		printf "FUNCTIONS ($FileBF)\n\n"

		while read; do
			if ! [ -z "$REPLY" ] && ! [[ $REPLY =~ ^\# ]]; then
				if [[ $REPLY =~ [a-Z0-9_-]+\(\)[\{\(] ]]; then
					Name=${REPLY%%\(\)[\(\{]*}

					# A description of " #: TEXT" must be appended to
					# the function call line for each function. This
					# will NOT work otherwise.
					Desc=${REPLY#*\#\:}

					# Only functions found 0-1 tabs in are counted.
					if [[ $Name =~ ^\	{0,1}[a-Z_-] ]]; then
						Print "${Name//\	/}" "${Desc#\ }"
					fi
				fi
			fi
		done < "$FileBF"
	else
		Err 1 "File '$FileBF' not found."
	fi
fi

# Gather aliases.
if [ "$OnlyAlias" == 'true' ] || [ -z "$OnlyFunc" -a -z "$OnlyAlias" ]; then
	if [ -f "$FileBA" ] && [ -r "$FileBA" ]; then
		printf "${NL}ALIASES ($FileBA)\n\n"

		while read; do
			if ! [ -z "$REPLY" ] && ! [[ $REPLY =~ ^\# ]]; then
				if [[ $REPLY =~ alias\ [:\"\']{0,}[a-Z0-9_-]+[\'\"]{0,}\= ]]; then
					declare -a Temp=(${REPLY%%\=*})

					#TODO - A cleaner system is preferable.
					# A description of " #: TEXT" must be appended to
					# the alias set line for each function. This will
					# NOT work otherwise, as with the functions.
					Desc=${REPLY#*\#\:}

					Print "${Temp[1]//[\"\']}" "${Desc#\ }"
				fi
			fi
		done < "$FileBA"
	else
		Err 1 "File '$FileBA' not found."
	fi
fi
